vich_uploader:
    db_driver: orm

    mappings:
       artistImage:
           uri_prefix: '%uploads_path_artists%'
           upload_destination: '%kernel.project_dir%/public/%uploads_path_artists%'
       eventImage:
           uri_prefix: '%uploads_path_events%'
           upload_destination: '%kernel.project_dir%/public/%uploads_path_events%'
       galleryImage:
           uri_prefix: '%uploads_path_gallery%'
           upload_destination: '%kernel.project_dir%/public/%uploads_path_gallery%'
       articlesImage:
           uri_prefix: '%uploads_path_articles%'
           upload_destination: '%kernel.project_dir%/public/%uploads_path_articles%'
