easy_admin:
  design:
      brand_color: '#42a7ff'
      menu:
        - { label: 'Blog', entity: 'Article', icon: 'newspaper' }
        - { label: 'Gallerie', entity: 'GalleryEntity', icon: 'images' }

        - { label: 'Spectacles', icon: 'calendar-alt'}          
        - { label: 'Spectacles', entity: 'Event', icon: 'calendar-alt' }
        - { label: 'Artistes', entity: 'Artist', icon: 'users' }
        - { label: 'Categories', entity: 'Category', icon: 'tags' }
        - { label: 'Lieux', entity: 'Location', icon: 'map-marked-alt' }
        
        - { label: 'Apparence', icon: 'paint-brush'}
        - { label: "Heures d'ouvetures", entity: 'OpenHours', icon: 'clock' }
        - { label: 'Generale', entity: 'Website', icon: 'sliders-h' }
        
        - label: 'Administrateur'
          icon: 'cogs'
          children:
              - { label: 'Roles', entity: 'Role', icon: 'user-shield' }
              - { label: 'Utilisateurs', entity: 'User', icon: 'users' }