easy_admin:
  entities:
    Article:
        class: App\Entity\Article
        form:
          title: "Créer un article"
          fields:
              - { type: 'group', columns: 8, label: 'Article' }
              - { property: 'title', type: 'text', label: "Titre", css_class: 'large' }
              - { property: 'content', type: 'text_editor', label: "Contenu" }

              - { type: 'group', columns: 4, label: 'Informations complémentaire' }
              - { property: 'thumbnailFile', type: 'vich_image', label: 'Image de mise en avant', type_options: { required: true } }
              - { property: 'author', label: "Auteur" }
              - { property: 'activated', type: 'checkbox', label: "Cacher" }
        list:
          title: "Articles"
          fields:
              - { property: 'thumbnail', type: 'image', base_path: '%uploads_path_articles%' }
              - { property: 'title', type: 'text', label: "Titre" }
              - { property: 'createdAt', label: "Création", format: 'j/m/Y'}
              - { property: 'updatedAt', label: "Modification", format: 'j/m/Y'}
              - { property: 'author', type: 'text' }
              - { property: 'activated', type: 'toggle', label: "Cacher" }
          actions:
              - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
              - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }